version: '3'
services: 
  ouroboros:
    hostname: ouroboros
    image: pyouroboros/ouroboros
    environment:
      CLEANUP: "true"
      INTERVAL: 300
      LOG_LEVEL: info
      SELF_UPDATE: "true"
      TZ: IST
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - xonglcloud

  db:
    image: mysql:latest
    volumes:
      - "./.data/db:/var/lib/mysql"
      - "./.data/conf/mysql:/etc/mysql/conf.d"
    restart: always    
    environment:
      MYSQL_ROOT_PASSWORD: ldap
      MYSQL_DATABASE: ldap
      MYSQL_USER: xongl
      MYSQL_PASSWORD: ldap
    networks:
      - xonglcloud
      
  ldap-client:
    image: osixia/phpldapadmin:latest
    hostname: xongldata
    domainname: ldap.xongl.com
    depends_on:
      - db
      - ldap
    links:
      - db
      - ldap:ldap.xongl.com
    ports: 
      - "6444:443" 
    restart: always
    environment:
      LDAP_DB_HOST: db:3306
      LDAP_DB_PASSWORD: ldap
      LDAP_DB_USER: xongl
      LDAP_DB_NAME: ldap
      PHPLDAPADMIN_LDAP_HOSTS: "ldap"  
      PHPLDAPADMIN_LDAP_CLIENT_TLS: "false"
    networks:
      - xonglcloud

  ldap:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: ./Dockerfile   
    container_name: ldap
    hostname: xongldata
    domainname: ldap.xongl.com
    ports:
      - "390:389"
    volumes:
      - "./.data/var/lib/ldap:/var/lib/ldap"
      - "./.data/etc/ldap/slapd.d:/etc/ldap/slapd.d"
    links:
      - db
    restart: always
    networks:
      - xonglcloud

  ldapbackup:
    depends_on:
      - db
      - ldap  
    image: osixia/openldap-backup:latest  
    hostname: xongldata
    domainname: ldap.xongl.com
    volumes:
      - "./.data/openldap/backup:/data/backup"
      - "./.data/etc/ldap/slapd.d:/etc/ldap/slapd.d"
    links:
      - db
      - ldap:ldap.xongl.com
    restart: always    
    environment: 
      LDAP_DB_HOST: db:3306
      LDAP_DB_PASSWORD: ldap
      LDAP_DB_USER: xongl
      LDAP_DB_NAME: ldap 
      LDAP_ORGANISATION: xongl
      LDAP_DOMAIN: ldap.xongl.com
      LDAP_ADMIN_PASSWORD: ldap
      LDAP_BACKUP_CONFIG_CRON_EXP: "0 5 * * *"
      LDAP_BACKUP_DATA_CRON_EXP: "0 5 * * *"
    networks:
      - xonglcloud

volumes:
    .data:
  
networks: 
  xonglcloud:
    driver: bridge