version: "3.5"

services:
  app:
    image: app
    container_name: app
    build:
      context: .
      dockerfile: ./app/Dockerfile
    restart: unless-stopped
    hostname: exampledata
    domainname: ldap.example.com
    depends_on:
      - ldap
    ports:
      - "3000:3000"
    networks:
      - examplecloud

  ouroboros:
    hostname: ouroboros
    image: pyouroboros/ouroboros
    container_name: ouroboros
    environment:
      CLEANUP: "true"
      INTERVAL: 300
      LOG_LEVEL: info
      SELF_UPDATE: "true"
      TZ: IST
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - examplecloud

  db:
    image: mysql:latest
    container_name: db
    volumes:
      - "./.data/db:/var/lib/mysql"
      - "./.data/conf/mysql:/etc/mysql/conf.d"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ldap
      MYSQL_DATABASE: ldap
      MYSQL_USER: example
      MYSQL_PASSWORD: ldap
    networks:
      - examplecloud

  ldap-client:
    image: osixia/phpldapadmin:latest
    container_name: ldap-client
    hostname: exampledata
    domainname: ldap.example.com
    depends_on:
      - db
      - ldap
    links:
      - db
      - ldap:ldap.example.com
    ports:
      - "6444:443"
    restart: unless-stopped
    command: --copy-service
    environment:
      LDAP_DB_HOST: db:3306
      LDAP_DB_PASSWORD: ldap
      LDAP_DB_USER: example
      LDAP_DB_NAME: ldap
      PHPLDAPADMIN_LDAP_HOSTS: "ldap"
      PHPLDAPADMIN_LDAP_CLIENT_TLS: "false"
    networks:
      - examplecloud

  ldap:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: ldap
    hostname: exampledata
    domainname: ldap.example.com
    ports:
      - "390:389"
    volumes:
      - "./.data/var/lib/ldap:/var/lib/ldap"
      - "./.data/etc/ldap/slapd.d:/etc/ldap/slapd.d"
    links:
      - db
    restart: unless-stopped
    networks:
      - examplecloud

  ldapbackup:
    depends_on:
      - db
      - ldap
    image: osixia/openldap-backup:latest
    hostname: exampledata
    domainname: ldap.example.com
    volumes:
      - "./.data/openldap/backup:/data/backup"
      - "./.data/etc/ldap/slapd.d:/etc/ldap/slapd.d"
    links:
      - db
      - ldap:ldap.example.com
    restart: unless-stopped
    environment:
      LDAP_DB_HOST: db:3306
      LDAP_DB_PASSWORD: ldap
      LDAP_DB_USER: example
      LDAP_DB_NAME: ldap
      LDAP_ORGANISATION: example
      LDAP_DOMAIN: ldap.example.com
      LDAP_ADMIN_PASSWORD: ldap
      LDAP_BACKUP_CONFIG_CRON_EXP: "0 5 * * *"
      LDAP_BACKUP_DATA_CRON_EXP: "0 5 * * *"
    networks:
      - examplecloud

volumes:
  .data:

networks:
  examplecloud: