FROM osixia/openldap:latest
MAINTAINER Saksham 

ADD bootstrap /container/service/slapd/assets/config/bootstrap
ADD environment /container/environment/01-custom
ADD certs /container/service/slapd/assets/certs